import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import PrefCheckBox from "../components/PrefCheckBox";
import { getPrefectures } from "./api/prefectures";
import type { PrefectureData } from "./api/prefectures";
import { useState } from "react";
type Props = {
  prefs: PrefectureData;
};

export async function getServerSideProps() {
  const prefs = await getPrefectures();
  return { props: { prefs } };
}

export default function Home(data: Props) {
  const [selectedPrefCodes, setSelectedPrefCode] = useState<Number[]>([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {data.prefs.result.map((n) => {
            return (
              <PrefCheckBox
                key={n.prefCode.toString()}
                name={n.prefName}
                code={n.prefCode}
                onChange={(c) => {
                  if (selectedPrefCodes.indexOf(c) === -1) {
                    setSelectedPrefCode(selectedPrefCodes.concat(c));
                  } else {
                    setSelectedPrefCode(
                      selectedPrefCodes.filter((n) => n !== c)
                    );
                  }
                }}
              ></PrefCheckBox>
            );
          })}
        </div>
        <label>selected:{selectedPrefCodes.join(", ")}</label>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
